[package]
name = "organizer"
version = "0.1.0"
authors = ["Daniel Wiberg <daniel@skillster.se>"]
build = "build.rs"

[dependencies]
libc = "0.2.18"
glutin = "0.7.0"
lazy_static = "0.2.2"

[build-dependencies]
gl_generator = "0.5.0"